stages:
  - build
  - deploy

variables:
  AWS_REGION: <your-aws-region>
  IMAGE_NAME: <your-image-name>
  ECR_REGISTRY: <your-ecr-registry>

build:
  image: docker:20.10.9
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $ECR_REGISTRY/$IMAGE_NAME
    - echo $AWS_ACCESS_KEY_ID | docker login -u AWS --password-stdin $ECR_REGISTRY
    - docker push $ECR_REGISTRY/$IMAGE_NAME

deploy:
  image: amazon/aws-cli:2.3.1
  stage: deploy
  script:
    - aws configure set region $AWS_REGION
    - aws ecs update-service --cluster <your-ecs-cluster-name> --service <your-ecs-service-name> --force-new-deployment
   only:
    - master